---
- name: Ensure required packages for repository
  package:
    name: "{{ item }}"
    state: present
  loop:
    - yum-utils
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
  when: ansible_os_family in ["RedHat", "Debian"]

- name: Add Docker GPG key (Debian)
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  when: ansible_os_family == "Debian"

- name: Add Docker yum repository
  ansible.builtin.yum_repository:
    name: docker
    description: "Docker CE Stable - $basearch"
    baseurl: >-
      https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Install Docker packages
  package:
    name: "{{ docker_packages[ansible_os_family] + docker_extra_packages }}"
    state: "{{ 'latest' if docker_version == 'latest' else 'present' }}"
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

- name: Ensure docker service is enabled and running
  service:
    name: docker
    state: started
    enabled: yes

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"
  when: docker_users | length > 0
  notify: restart docker
